const pad = (n) => String(n).padStart(2, '0')
const fmt = (d) =>
  `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`

export const iso = (offsetDays = 0) => {
  const d = new Date()
  d.setDate(d.getDate() + offsetDays)
  return fmt(d)
}
export function buildSeed() {
  const clients = [
    {
      id: 'c1',
      nombre: 'Banco del Istmo – Sucursal David',
      tipo: 'Empresa',
      contacto: 'Laura Fuentes',
      telefono: '+507 775-4120',
      email: 'lfuentes@bancoistmo.com.pa',
      ciudad: 'David',
      estado: 'Activo',
      lat: 8.4273,
      lng: -82.4308,
    },
    {
      id: 'c2',
      nombre: 'Centro Comercial Plaza Pacífico',
      tipo: 'Empresa',
      contacto: 'Andrés Rojas',
      telefono: '+507 774-3305',
      email: 'arojas@plazapacifico.com.pa',
      ciudad: 'David',
      estado: 'Activo',
      lat: 8.435,
      lng: -82.44,
    },
    {
      id: 'c3',
      nombre: 'Agroindustrias del Valle',
      tipo: 'Industrial',
      contacto: 'Marta Quiroga',
      telefono: '+507 6615-0103',
      email: 'mquiroga@agrovalle.com.pa',
      ciudad: 'Boquerón',
      estado: 'Activo',
      lat: 8.5167,
      lng: -82.6167,
    },
    {
      id: 'c4',
      nombre: 'PH Residencial Altos de Boquete',
      tipo: 'Residencial',
      contacto: 'Carlos Peña',
      telefono: '+507 720-1456',
      email: 'admin@altosboquete.com.pa',
      ciudad: 'Boquete',
      estado: 'Activo',
      lat: 8.78,
      lng: -82.4333,
    },
    {
      id: 'c5',
      nombre: 'Municipio de Barú',
      tipo: 'Gobierno',
      contacto: 'Sofía Duarte',
      telefono: '+507 770-8812',
      email: 'sduarte@municipiobaru.gob.pa',
      ciudad: 'Puerto Armuelles',
      estado: 'Prospecto',
      lat: 8.2833,
      lng: -82.8667,
    },
    {
      id: 'c6',
      nombre: 'Logística Paso Canoas S.A.',
      tipo: 'Industrial',
      contacto: 'Iván Morales',
      telefono: '+507 6720-0106',
      email: 'imorales@logpasocanoas.com.pa',
      ciudad: 'Paso Canoas',
      estado: 'Inactivo',
      lat: 8.5333,
      lng: -82.8333,
    },
  ]
  const agents = [
    {
      id: 'a1',
      nombre: 'Jorge Ramírez',
      documento: '4-712-1458',
      cargo: 'Supervisor',
      telefono: '+507 6612-0201',
      sitio: 'c1',
      estado: 'Activo',
      licencia: iso(210),
      ingreso: iso(-900),
      emergencia: 'María Ramírez · +507 6700-1122',
    },
    {
      id: 'a2',
      nombre: 'Luis Herrera',
      documento: '4-745-0932',
      cargo: 'Guardia',
      telefono: '+507 6618-0202',
      sitio: 'c1',
      estado: 'Activo',
      licencia: iso(90),
      ingreso: iso(-620),
      emergencia: 'Rosa Herrera · +507 6655-3344',
    },
    {
      id: 'a3',
      nombre: 'Pedro Samudio',
      documento: '4-701-2210',
      cargo: 'Guardia',
      telefono: '+507 6624-0203',
      sitio: 'c2',
      estado: 'Activo',
      licencia: iso(25),
      ingreso: iso(-480),
      emergencia: 'Ana Samudio · +507 6680-9087',
    },
    {
      id: 'a4',
      nombre: 'Diana Salazar',
      documento: '4-788-3341',
      cargo: 'Operador CCTV',
      telefono: '+507 6631-0204',
      sitio: 'c2',
      estado: 'Activo',
      licencia: iso(300),
      ingreso: iso(-350),
      emergencia: 'Jorge Salazar · +507 6699-4410',
    },
    {
      id: 'a5',
      nombre: 'Miguel Batista',
      documento: '4-690-7765',
      cargo: 'Escolta',
      telefono: '+507 6645-0205',
      sitio: 'c3',
      estado: 'Descanso',
      licencia: iso(150),
      ingreso: iso(-1100),
      emergencia: 'Luisa Batista · +507 6611-2290',
    },
    {
      id: 'a6',
      nombre: 'Camila Pittí',
      documento: '4-802-1190',
      cargo: 'Guardia',
      telefono: '+507 6652-0206',
      sitio: 'c4',
      estado: 'Activo',
      licencia: iso(-10),
      ingreso: iso(-200),
      emergencia: 'Rubén Pittí · +507 6677-5521',
    },
    {
      id: 'a7',
      nombre: 'Ricardo Araúz',
      documento: '4-733-6608',
      cargo: 'Guardia',
      telefono: '+507 6660-0207',
      sitio: 'c3',
      estado: 'Licencia',
      licencia: iso(60),
      ingreso: iso(-740),
      emergencia: 'Elena Araúz · +507 6688-7013',
    },
  ]
  const contracts = [
    {
      id: 'k1',
      cliente: 'c1',
      servicio: 'Vigilancia física',
      agentes: 6,
      valor: 18500,
      inicio: iso(-400),
      fin: iso(330),
      estado: 'Vigente',
    },
    {
      id: 'k2',
      cliente: 'c2',
      servicio: 'Monitoreo CCTV',
      agentes: 3,
      valor: 9200,
      inicio: iso(-250),
      fin: iso(115),
      estado: 'Vigente',
    },
    {
      id: 'k3',
      cliente: 'c3',
      servicio: 'Escolta y patrullaje',
      agentes: 4,
      valor: 12800,
      inicio: iso(-120),
      fin: iso(245),
      estado: 'Vigente',
    },
    {
      id: 'k4',
      cliente: 'c4',
      servicio: 'Vigilancia física',
      agentes: 2,
      valor: 5400,
      inicio: iso(-700),
      fin: iso(20),
      estado: 'Por vencer',
    },
    {
      id: 'k5',
      cliente: 'c6',
      servicio: 'Alarmas y sensores',
      agentes: 0,
      valor: 2100,
      inicio: iso(-500),
      fin: iso(-30),
      estado: 'Vencido',
    },
  ]
  // Rotación de 4 puestos con turnos de 12 h (día 06-18, noche 18-06) para que siempre haya agentes en servicio
  const shifts = []
  const pool = ['a1', 'a2', 'a3', 'a4', 'a6']
  for (let d = -12; d <= 20; d++) {
    const slot = (k) => pool[(((d + k) % 5) + 5) % 5]
    const estado = d < 0 ? (d === -2 ? 'Ausente' : 'Completado') : 'Programado'
    shifts.push(
      {
        id: `s${d}a`,
        agente: slot(0),
        cliente: 'c1',
        fecha: iso(d),
        inicio: '06:00',
        fin: '18:00',
        tipo: 'Diurno',
        estado,
      },
      {
        id: `s${d}b`,
        agente: slot(1),
        cliente: 'c2',
        fecha: iso(d),
        inicio: '06:00',
        fin: '18:00',
        tipo: 'Diurno',
        estado,
      },
      {
        id: `s${d}c`,
        agente: slot(2),
        cliente: 'c3',
        fecha: iso(d),
        inicio: '18:00',
        fin: '06:00',
        tipo: 'Nocturno',
        estado,
      },
      {
        id: `s${d}d`,
        agente: slot(3),
        cliente: 'c4',
        fecha: iso(d),
        inicio: '18:00',
        fin: '06:00',
        tipo: 'Nocturno',
        estado,
      },
    )
  }
  const incidents = [
    {
      id: 'i1',
      titulo: 'Intento de ingreso no autorizado',
      cliente: 'c3',
      agente: 'a5',
      fecha: iso(-1),
      severidad: 'Alta',
      estado: 'En curso',
      descripcion:
        'Persona intentó acceder por la puerta de carga trasera de la planta en Boquerón.',
    },
    {
      id: 'i2',
      titulo: 'Falla en cámara perimetral #4',
      cliente: 'c2',
      agente: 'a4',
      fecha: iso(-2),
      severidad: 'Media',
      estado: 'Abierto',
      descripcion: 'Sin señal desde las 02:10.',
    },
    {
      id: 'i3',
      titulo: 'Alarma activada fuera de horario',
      cliente: 'c1',
      agente: 'a1',
      fecha: iso(-5),
      severidad: 'Crítica',
      estado: 'Resuelto',
      descripcion: 'Falsa alarma por sensor de movimiento defectuoso.',
    },
    {
      id: 'i4',
      titulo: 'Vehículo mal estacionado en acceso',
      cliente: 'c4',
      agente: 'a6',
      fecha: iso(-9),
      severidad: 'Baja',
      estado: 'Resuelto',
      descripcion: '',
    },
    {
      id: 'i5',
      titulo: 'Robo menor en parqueadero',
      cliente: 'c2',
      agente: 'a3',
      fecha: iso(-34),
      severidad: 'Alta',
      estado: 'Resuelto',
      descripcion: '',
    },
    {
      id: 'i6',
      titulo: 'Puerta de emergencia forzada',
      cliente: 'c3',
      agente: 'a7',
      fecha: iso(-62),
      severidad: 'Media',
      estado: 'Resuelto',
      descripcion: '',
    },
    {
      id: 'i7',
      titulo: 'Radio fuera de servicio',
      cliente: 'c1',
      agente: 'a2',
      fecha: iso(-95),
      severidad: 'Baja',
      estado: 'Resuelto',
      descripcion: '',
    },
  ]
  const leads = [
    {
      id: 'l1',
      empresa: 'Hotel Mirador de Boquete',
      contacto: 'Renata Gil',
      telefono: '+507 6701-0301',
      servicio: 'Vigilancia física',
      valor: 14000,
      etapa: 'Nuevo',
    },
    {
      id: 'l2',
      empresa: 'Clínica San Lucas David',
      contacto: 'Pablo Ríos',
      telefono: '+507 775-2230',
      servicio: 'Monitoreo CCTV',
      valor: 8700,
      etapa: 'Contactado',
    },
    {
      id: 'l3',
      empresa: 'Instituto Superior Chiricano',
      contacto: 'Ana Beltrán',
      telefono: '+507 6714-0303',
      servicio: 'Vigilancia física',
      valor: 22000,
      etapa: 'Cotizado',
    },
    {
      id: 'l4',
      empresa: 'Supermercados Ahorro Chiriquí',
      contacto: 'Hugo Páez',
      telefono: '+507 6728-0304',
      servicio: 'Alarmas y sensores',
      valor: 6400,
      etapa: 'Negociación',
    },
    {
      id: 'l5',
      empresa: 'Constructora Volcán Altos',
      contacto: 'Nora Ibarra',
      telefono: '+507 6735-0305',
      servicio: 'Escolta y patrullaje',
      valor: 9800,
      etapa: 'Ganado',
    },
  ]
  const equipment = [
    {
      id: 'e1',
      nombre: 'Radio Motorola T800',
      tipo: 'Radio',
      serie: 'MT-8821',
      asignado: 'a1',
      estado: 'Asignado',
    },
    {
      id: 'e2',
      nombre: 'Radio Motorola T800',
      tipo: 'Radio',
      serie: 'MT-8822',
      asignado: 'a2',
      estado: 'Asignado',
    },
    {
      id: 'e3',
      nombre: 'Cámara corporal Axon',
      tipo: 'Cámara',
      serie: 'AX-1190',
      asignado: '',
      estado: 'Disponible',
    },
    {
      id: 'e4',
      nombre: 'Camioneta patrulla 03',
      tipo: 'Vehículo',
      serie: 'PLC-303',
      asignado: 'a5',
      estado: 'Asignado',
    },
    {
      id: 'e5',
      nombre: 'Detector de metales',
      tipo: 'Detector',
      serie: 'DM-452',
      asignado: '',
      estado: 'Mantenimiento',
    },
  ]
  return { clients, agents, contracts, shifts, incidents, leads, equipment }
}
